# Generated by Django 5.0.6 on 2024-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_covered', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_hours', models.PositiveIntegerField()),
                ('time_minutes', models.PositiveIntegerField()),
                ('time_seconds', models.PositiveIntegerField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('achievement_date', models.DateField()),
                ('achievement_photo', models.ImageField(max_length=255, upload_to='img')),
            ],
        ),
    ]
