# Generated by Django 5.0.6 on 2024-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0005_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='img/default_profile.png', upload_to='img'),
        ),
    ]
